name: Documentation
on:
  push:
    branches:
      - test_sphinx-build

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv install --dev
        pipenv install sphinx
        pipenv install sphinx_rtd_theme 
    - name: Build docs
      run: |
        pipenv shell
        sphinx-apidoc -f -o docs meilisearch/
        sphinx-build docs ./docs/_build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
        force_orphan: true
